### ISSUE TITLE
Emoji not being drawn

### ISSUE THREAD

**Issue by edugomez102** [vierofernando/twemoji-parser#4]
Hi, I've run the basic example and this is what I get
![testparse](https://user-images.githubusercontent.com/50159560/109391496-adadf680-7917-11eb-8436-46c66540d747.png)

I am missing something?

Running python 3.8 on windows 10

**Comment by vierofernando** [comment]
Thanks for reporting this bug!

This bug should've been fixed and pushed to update 0.5.
Try updating your `twemoji-parser` version to 0.5 and this should work.

https://pypi.org/project/twemoji-parser/0.5/
