### ISSUE TITLE
Change emoji size

### ISSUE THREAD

**Issue by edugomez102** [vierofernando/twemoji-parser#5]
Hi, I've run the basic example and everything is working fine, but I find the emoji size quite bigger than the font, is there a way to make the emoji smaller? or make it like a 20% smaller
![testparse](https://user-images.githubusercontent.com/50159560/109393011-c1f5f180-791f-11eb-99e0-83a2abf13c02.png)

**Comment by vierofernando** [comment]
sure! i'll make this as an optional feature in the future; allowing the ability to explicitly change the emoji size.

**Comment by vierofernando** [comment]
this feature have been added with some other bug fixes in version 0.5.1!

https://pypi.org/project/twemoji-parser/0.5.1/

**Comment by edugomez102** [comment]
I've tried it and when making emojis smaller, emojis are not well aligned with text.

By the way, do you think it would be possible to reduce the quality loss of the emoji when making it smaller?
